### ISSUE TITLE
Sobre el dominio Klint-psk

### ISSUE THREAD

**Issue by Klint-psk** [romhackhispano/dns#1]
Buenas, veo que esto parece que está resucitando por aquí =D
Mi dominio, klint-psk.romhackhispano.org, no va. Además perdí los datos de acceso hace mucho en una migración y nunca pude volver a subir nada. ¿Se podría añadir de nuevo? ^^

**Comment by soywiz** [comment]
¿Tienes una copia de los datos? Porque no me suena haber visto ese subdominio en la copia que tengo. Si tienes una copia se puede crear aquí y lo volvemos a activar.

Saludos

**Comment by Klint-psk** [comment]
Yep, le voy a hacer una puesta a punto. ¿Por dónde te lo paso, se puede por aquí?

**Comment by soywiz** [comment]
https://github.com/romhackhispano/klint-psk.romhackhispano.org

**Comment by Klint-psk** [comment]
He tardado "un poco", pero ahora ya está.
Pero no se ven los cambios, la url sigue yéndose al index.html que ya no está, así que me he saltado algún paso con el 100% de seguridad. ¿Alguna indicación, si no es mucha molestia? ><

**Comment by soywiz** [comment]
Has puesto PHP en github. Ahí no chuta. Tiene que ser HTML puro sin PHP. Lo único que soporta github directamente es [jekyll](https://jekyllrb.com/).

En las webs de tales-tra lo que hice fue un pequeño script que generaba los html a partir de los PHP.

TOA (más elaborado):
https://github.com/talestra/toa.tales-tra.com/blob/gh-pages/build.php

TOE (más sencillo):
https://github.com/talestra/toe.tales-tra.com/blob/gh-pages/build.php

Si no lo tienes muy complicado, te aconsejaría usar jekyll que te va a dar más flexibilidad y es más "estándar".

**Comment by Klint-psk** [comment]
Mmm... podría redirigir Klint-psk.romhacking.org a donde yo quisiera, ¿no? Si lo subo a mi dominio y lo puedo mandar para allá sería mucho más simple. Pregunto, si no se puede pues miraré a ver de adaptar tu script. Es que tengo lecturas de XMLs y tal que no tengo ganas de rehacer en JS.

**Comment by soywiz** [comment]
Te miro de hacer yo el script. Si no te vale, ya rediriges. Dame un rato.

**Comment by Klint-psk** [comment]
De acuerdo. Pero si no te resulta conveniente no te preocupes, miro yo de adaptarlo luego, no quiero cargarte trabajo innecesariamente ><

**Comment by soywiz** [comment]
Ale ya lo tienes. En principio cuando actualices cosas, basta con que cambies algo, ejecutes build.php con alguna versión reciente de php y que subas los archivos generados.

Cierro esto :)
